<?php 
    $ajax_action = admin_url( 'admin-ajax.php' );
    $ajax_form_action = admin_url( 'admin-ajax.php' );
    $currentuser = wp_get_current_user();
    $userinfo = get_userdata($currentuser -> ID);
    $userid =  $currentuser -> ID;
    $form_action = admin_url( 'admin.php?page=atcontent/connect.php' );
    $email = $userinfo -> user_email;
    $username = $userinfo -> display_name;
    $site = $_SERVER['HTTP_HOST'];    
?>

<style>
    input {
        padding: 3px 8px;
        font-size: 1.7em;
        line-height: 100%;
        height: 1.7em;
        width: 300px;
        outline: 0;
        margin: 0 0 20px 0;3
        
    }
</style>
<script src="/wp-content/plugins/atcontent/interface.js" type="text/javascript"></script>
<script>
    var gate = '<?php echo admin_url('admin-ajax.php'); ?>';
    var email = '<?php echo $email; ?>';    
    var site = '<?php echo $site; ?>';
    var title = '<?php bloginfo('name'); ?>';
    var userid = '<?php echo $userid; ?>';
    
    window.CPlase_ga = window.CPlase_ga || [];
                CPlase_ga.push({
                    category: 'connectTab <?php echo AC_VERSION?>',
                    action: 'opened',
                    label: site + '      ' + email
                });
</script>
<form id="connect_form" method="post" action="<?php echo $form_action; ?>">
    <input type="hidden" name="atcontent_invite" value="Y">
<div class="atcontent_invite">
    <h1>Connect and complete the last step to increase your audience.</h1>
	<p style="font-size: 1.6em; margin: 1em 0px 0.5em;">The connection will create an account on AtContent.com.</p>
        <label for="email">For email </label></br>
        <input id="email" type="text" name="email" value="<?php echo $email?>"></input></br>
        <label for="email">And username</label></br>
        <input id="username" type="text" name="username" value="<?php echo $username?>"></input></br>
    <div id="ac_connect_result"></div>       
    <div class="discl">
        The account will be used to expand your audience, gather readership stats and improve SEO. You'll receive autogenerated password for created account on email
	</div>
	<a id="b_connect" class="likebutton b_green b_big" href="#">Connect with AtContent</a>
   <hr />
        
                    
                    <div class="addit">
                        What bloggers tweet about us
                    </div>

    <div style="width: 400px;margin: 0 auto;">
        <blockquote class="twitter-tweet" lang="en"><p>860% increase in readership in 3 weeks WordPress with AtContent — even better. Check it! <a href="http://t.co/STLK6S5xK1">http://t.co/STLK6S5xK1</a></p>&mdash; Christine Cope (@christine_cope) <a href="https://twitter.com/christine_cope/statuses/412073834557100032">December 15, 2013</a></blockquote>
        <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
    </div>
                
                    
<script type="text/javascript">
    (function ($) {  
      
        var apikey = '';  
        window.ac_connect_res = function (d) {
            if (d) document.getElementById("connect_form").submit();
            else $("#ac_connect_result").html(
                    'Something is wrong. <a href="javascript:window.location.reload();">Reload page</a> and try again, please.');
        }
        
        function ConnectBlog()    
        {

            var email = $("#email").val();
            $.ajax({
                url: '<?php echo $ajax_form_action; ?>',
			    type: 'post',
                data : {
                    action: 'atcontent_connect_blog',
                    email : email,
                    bloguserid : userid,
                    apikey : apikey,
                    sitetitle : title,
                    gate : gate
                },
			    dataType: "json"    
		    });  
        }
  

        function SaveCredentials(d)
        {
            apikey = d.APIKey;
            $.ajax({url: '<?php echo $ajax_form_action; ?>',
			    type: 'post',
			    data: {
					    action: 'atcontent_save_credentials',
                        apikey : d.APIKey,
                        nickname : d.Nickname,
                        showname: d.Showname,
                        Avatar20 : d.Avatar20,
                        Avatar80 : d.Avatar80
					},                
			    dataType: "json"
		    });  
        }

        function AutoSignIn()
        {
            var email = $("#email").val();
            $.ajax({
                url: 'http://www.atcontent.com/api/v1/native/checkauth.ashx',
                jsonp: 'jsonp_callback',
                data : {
                    email : email
                },
                success: function(d){
                    if (d.IsOK)
                    {
                        SaveCredentials(d);
                        ConnectBlog();
                    }
                    else
                    {
                        alert('none');
                    }
                },
                error: function() {					
					$("#ac_connect_result").html('Something is wrong. <a href="javascript:window.location.reload();">Reload page</a> and try again, please.');
				},
			    dataType: "jsonp"    
		    });  
        }
        
        $("#b_connect").click(function () {
             var email = $("#email").val();
             var username = $("#username").val();
             $.ajax({url: '<?php echo $ajax_form_action; ?>',
			    type: 'post',
			    data: {
					    action: 'atcontent_connect',
                        email : email,
                        username : username,
                        title : title
					},
                success: function(d){
					if (d.IsOK)
                    {
                        SaveCredentials(d);
                        ConnectBlog();
                    }else
                    {
                        if (d.Error.indexOf("exist")!=-1) 
                        {
                            AutoSignIn();
                        }
                        $("#ac_connect_result").html(d.Error);
                    }
				},
				error: function() {					
					$("#ac_connect_result").html('Something is wrong. <a href="javascript:window.location.reload();">Reload page</a> and try again, please.');
				},
			    dataType: "json"
		    });  
        });
    })(jQuery);
</script>
</div>
</form>
