<?php 
    $ajax_action = admin_url( 'admin-ajax.php' );
    $ajax_form_action = admin_url( 'admin-ajax.php' );
    $currentuser = wp_get_current_user();
    $userinfo = get_userdata($currentuser -> ID);
    $userid =  $currentuser -> ID;
    $form_action = admin_url( 'admin.php?page=atcontent/connect.php' );
    $email = $userinfo -> user_email;
    $username = $userinfo -> display_name;
    $site = $_SERVER['HTTP_HOST']; 
       
?>

<style>
    input {
        padding: 3px 8px;
        font-size: 1.7em;
        line-height: 100%;
        height: 1.7em;
        width: 300px;
        outline: 0;
        margin: 0 0 20px 0;
    }

    .blogs {
        text-align: left;
        width: 30%;
        margin-left: 35%;
        font-size: 18px;
        margin-bottom: 20px;
    }

    #blog_data_form {
        margin-bottom: -20px;
    }
    
    .blogs > input
    {
        margin-top: 10px;
        margin-bottom: 8px;
    }
    
    .b_enable {
        background: none repeat scroll 0 0 #808080;
        color: #FFFFFF !important;
    }
</style>
<script src="/wp-content/plugins/atcontent/interface.js" type="text/javascript"></script>
<script>
    var gate = '<?php echo admin_url('admin-ajax.php'); ?>';
    var email = '<?php echo $email; ?>';    
    var site = '<?php echo $site; ?>';
    var title = '<?php bloginfo('name'); ?>';
    var userid = '<?php echo $userid; ?>';
    
    window.CPlase_ga = window.CPlase_ga || [];
                CPlase_ga.push({
                    category: 'connectTab <?php echo AC_VERSION?>',
                    action: 'opened',
                    label: site + '      ' + email
                });
</script>
<form id="connect_form" method="post" action="<?php echo $form_action; ?>">
    <input type="hidden" name="atcontent_invite" value="Y">
<div class="atcontent_invite">
    <h1>Connect and complete the last step to increase your audience.</h1>
	<p style="font-size: 1.6em; margin: 1em 0px 0.5em;">The connection will create an account on AtContent.com.</p>
        <div id="user_data_form">
            <label for="email">For email </label></br>
            <input id="email" type="text" name="email" value="<?php echo $email?>"></input></br>
            <label for="email">And username</label></br>
            <input id="username" type="text" name="username" value="<?php echo $username?>"></input></br>
        </div>
        
    <div id="ac_connect_result"></div>       
    <div class="discl">
        The account will be used to expand your audience, gather readership stats and improve SEO. You'll receive autogenerated password for created account on email
	</div>
	<a id="b_connect" class="likebutton b_green b_big" href="#">Connect with AtContent</a>
   <hr />
        
                    
                    <div class="addit">
                        What bloggers tweet about us
                    </div>

    <div style="width: 400px;margin: 0 auto;">
        <blockquote class="twitter-tweet" lang="en"><p>860% increase in readership in 3 weeks WordPress with AtContent — even better. Check it! <a href="http://t.co/STLK6S5xK1">http://t.co/STLK6S5xK1</a></p>&mdash; Christine Cope (@christine_cope) <a href="https://twitter.com/christine_cope/statuses/412073834557100032">December 15, 2013</a></blockquote>
        <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
    </div>
                
                    
<script type="text/javascript">
    var ConnectBlog;
    var AutoSignIn;

    function signInWindow()
    {
        email = document.getElementById("email").value;
        _window = window.open("http://www.atcontent.com/Auth/SignInWP?email="+email, "ac_auth", "width=460,height=420,resizable=no,scrollbars=no,status=yes,menubar=no,toolbar=no,location=yes,directories=no")
        _window.opener = window;
        setTimeout(function () {
            if (_window.closed)
                AutoSignIn();
            else
                setTimeout(arguments.callee, 10);
        }, 10);

    }

    (function ($) {  
        var buttonDisabled = false;
        var credentials;
        var apikey = '';  
        var selectedBlog = '';
        window.ac_connect_res = function (d) {
            if (d) document.getElementById("connect_form").submit();
            else $("#ac_connect_result").html(
                    'Something is wrong. <a href="javascript:window.location.reload();">Reload page</a> and try again, please.');
        }

        function DisableButton()
        {    
            $("#b_connect").removeClass('b_green').addClass('b_enable');
            buttonDisabled = true;
        }

        function EnableButton()
        {    
            $("#b_connect").addClass('b_green').removeClass('b_enable');
            buttonDisabled = false;
        }

        function CreateBlogsPanel(blogs)
        {
            $("#site").val(title);
            var blogsHtml = '<h2>You already have one or more AtContent blogs. You can choose your old blog or create a new one</h2><div class="blogs">';
            for (var i in blogs) {
                blogsHtml += '<input type="radio" onclick="javascript:jQuery(\'#blog_data_form\').hide();" name="blog" class="blog_radio" id="blog_' + blogs[i].BlogId + '" value="' + blogs[i].BlogId + '"/><label for="blog_' + blogs[i].BlogId + '">' + blogs[i].BlogTitle + '</label><br>';
            }
            blogsHtml += '<input type="radio" onclick="javascript:jQuery(\'#blog_data_form\').show();" name="blog" class="blog_radio" id="blog_new" value="-1"/><label for="blog_new">Create new blog</label><br></div><div id="blog_data_form" style="display: none;"><label for="email">New blog title </label></br><input id="site" type="text" name="site" value=""></input></br></div>'
            $("#user_data_form").hide();
            $("#b_connect").unbind('click').click(function()
            {
                title  = $("#site").val();
                var blog = $('input:radio[name=blog]:checked').val();
                if (blog!=null)
                {
                    DisableButton();
                    $("#blog_data_form").hide();
                    ConnectBlog(blog);
                } 
            });
            $("#ac_connect_result").html(blogsHtml);
        }
        
        ConnectBlog = function (selectedBlog)    
        {
            selectedBlog = selectedBlog || "";
            if (selectedBlog!="") $("#ac_connect_result").html("<h2>Last actions</h2>");
            
            var email = $("#email").val();
            $.ajax({
                url: '<?php echo $ajax_form_action; ?>',
			    type: 'post',
                data : {
                    action: 'atcontent_connect_blog',
                    email : email,
                    bloguserid : userid,
                    apikey : credentials.APIKey,
                    sitetitle : title,
                    gate : gate,
                    blog: selectedBlog
                },
                success: function(d){
                    if (d.IsOK)
                    {
                        SaveCredentials();                        
                    }
                    else
                    {
                        if(d.Error == "select")
                        {
                            CreateBlogsPanel(d.blogs);     
                            EnableButton();                       
                        }
                        else
                        {
                            $("#ac_connect_result").html(
                                        'Something is wrong. <a href="javascript:window.location.reload();">Reload page</a> and try again, please.');
                            EnableButton();  
                        }
                    }
                },
			    dataType: "json"    
		    });  
        }
  
   
        function SaveCredentials()
        {
            $.ajax({url: '<?php echo $ajax_form_action; ?>',
			    type: 'post',
			    data: {
					    action: 'atcontent_save_credentials',
                        apikey : credentials.APIKey,
                        nickname : credentials.Nickname,
                        showname: credentials.Showname,
                        Avatar20 : credentials.Avatar20,
                        Avatar80 : credentials.Avatar80
					}, 
                success: function(d)
                {  
                    $("#ac_connect_result").html('<h2>Congratulations you are successfull conected</h2>');
                    location.href = "?page=atcontent/settings.php"
                },                   
			    dataType: "json"
		    });
        }

        AutoSignIn = function()
        {
            DisableButton();
            var email = $("#email").val();
            $.ajax({
                url: 'http://www.atcontent.com/api/v1/native/checkauth.ashx',
                jsonp: 'jsonp_callback',
                data : {
                    email : email
                },
                success: function(d){
                    if (d.IsOK)
                    {
				        $("#ac_connect_result").html('<h2>Looking for your blogs</h2>');
                        credentials = d;
                        ConnectBlog();
                    }
                    else
                    {
                        EnableButton();
                        signInWindow();
                    }
                },
                error: function() {					
					$("#ac_connect_result").html('Something is wrong. <a href="javascript:window.location.reload();">Reload page</a> and try again, please.');
				},
			    dataType: "jsonp"    
		    });  
        }
        
        $("#b_connect").click(function () {
            $(".discl").html('');
		    $("#ac_connect_result").html('<h2>Trying to create account for you</h2>');
            if (buttonDisabled) {return;}
            DisableButton();
            var email = $("#email").val();
            var username = $("#username").val();
            $.ajax({url: '<?php echo $ajax_form_action; ?>',
			type: 'post',
			data: {
					action: 'atcontent_connect',
                    email : email,
                    username : username
				},
            success: function(d){
				if (d.IsOK)
                {
                    credentials = d;
				    $("#ac_connect_result").html('<h2>Create AtContent blog for you</h2>');
                    ConnectBlog();
                }else
                {
                    if (d.Error.indexOf("email already exist")!=-1) 
                    {
				        $("#ac_connect_result").html('<h2>We found your account, trying to sign in</h2>');
                        AutoSignIn();
                    }
                    else
                    {
                        $("#ac_connect_result").html(d.Error);
                        EnableButton();
                    }
                }
			},
			error: function() {
				$("#ac_connect_result").html('Something is wrong. <a href="javascript:window.location.reload();">Reload page</a> and try again, please.');
			},
			dataType: "json"
		});
    });
})(jQuery);
</script>
</div>
</form>
